### ISSUE TITLE
Consider changing project name

### ISSUE THREAD

**Issue by conorpp** [conorpp/u2f-one#2]
U2F one doesn't really fit since the standard is called FIDO 2.0

**Comment by 0x0ece** [comment]
FIDO2.zero?

**Comment by pjz** [comment]
OSKey-one (with u2f-zero being retroactive renamed to OSKey-zero) ?  OS = Open Source, which I think is one of the distinguishing features of this.

I do vote for a protcol-independent name, though, so you don't have to keep changing it with successive versions.  The purpose is staying the same, after all.

**Comment by conorpp** [comment]
I open sourced the code I was working on, under a different account:
https://github.com/SoloKeysSec/solo

A bit confusing since I opened this repo to start.

Hope you like the name Solo :)

**Comment by pjz** [comment]
Yeah, I found it eventually :) :+1:  This is closable now.  And you should archive this repo after putting a note point to SoloKeysSec/solo in the toplevel README :)
